# dongxi_dev: only used in local machine
development:
  WEIBO_APPKEY:         "1552726334"
  WEIBO_APPSECRET:      "bd6fa1e59dea33a79fbeec2a2a836413"
  WEIBO_ACCESS_TOKEN:   "2.00_aF2OEIDFFhB30536bf8370ZsA6Y"
test:
  WEIBO_APPKEY:         "1552726334"
  WEIBO_APPSECRET:      "bd6fa1e59dea33a79fbeec2a2a836413"
  WEIBO_ACCESS_TOKEN:   "2.00_aF2OEIDFFhB30536bf8370ZsA6Y"
# dongxi_pro: only used in staging/testing machine and production machine
production:
  WEIBO_APPKEY:         "2645092102"
  WEIBO_APPSECRET:      "3b4aa9e6f485ea33ad17407835e88314"
  WEIBO_ACCESS_TOKEN:   "2.00_aF2OEqRXAtC2fd33143edtCrzSE"
