default: &default
  adapter: postgresql
  database: dongxi_<%= Rails.env %>
  username: [your_username]
  password: [your_password]
  host: 127.0.0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
